INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title1", "category", 18, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title1", "category", 18, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title1", "category", 18, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title1", "category", 18, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title1", "category", 18, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title1", "category", 18, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title1", "category", 18, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title1", "category", 18, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title1", "category", 18, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title1", "category", 18, "date", "date");
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO users (name, age) VALUES ("george", 18);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
