INSERT INTO users (name, age) VALUES ("Ernest", 15);
INSERT INTO users (name, age) VALUES ("Shivone", 14);
INSERT INTO users (name, age) VALUES ("Carmen", 13);
INSERT INTO users (name, age) VALUES ("Daniel", 12);
INSERT INTO users (name, age) VALUES ("Aaron", 11);
INSERT INTO users (name, age) VALUES ("Chloe", 10);
INSERT INTO users (name, age) VALUES ("Jayla", 9);
INSERT INTO users (name, age) VALUES ("Lina", 8);
INSERT INTO users (name, age) VALUES ("Greg", 7);
INSERT INTO users (name, age) VALUES ("Pat", 6);
INSERT INTO users (name, age) VALUES ("Gerard", 5);
INSERT INTO users (name, age) VALUES ("Savvy", 4);
INSERT INTO users (name, age) VALUES ("Mike", 3);
INSERT INTO users (name, age) VALUES ("Ashley", 2);
INSERT INTO users (name, age) VALUES ("Sonic", 3);
INSERT INTO users (name, age) VALUES ("Rob", 1);
INSERT INTO users (name, age) VALUES ("Holmes", 17);
INSERT INTO users (name, age) VALUES ("Harry", 31);
INSERT INTO users (name, age) VALUES ("Steph", 23);
INSERT INTO users (name, age) VALUES ("Angie", 43);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title1", "Games", 500, 6/9, 6/10);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title2", "Books", 500, 6/11, 6/12);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title3", "Clothes", 500, 6/13, 6/14);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title4", "Love", 500, 6/15, 6/16);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title5", "Travel", 500, 6/17, 6/18);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title6", "Nature", 500, 6/19, 6/21);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title7", "School", 500, 6/21, 6/23);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title8", "Cars", 500, 6/23, 6/25);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title9", "Space", 500, 6/24, 6/27);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title10", "Food", 500, 6/27, 6/29);

INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (11, 11, 11);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12, 12, 12);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13, 13, 13);
INSERT INTO pledges (amount, user_id, project_id) VALUES (14, 14, 14);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 15, 15);
INSERT INTO pledges (amount, user_id, project_id) VALUES (16, 16, 16);
INSERT INTO pledges (amount, user_id, project_id) VALUES (17, 17, 17);
INSERT INTO pledges (amount, user_id, project_id) VALUES (18, 18, 18);
INSERT INTO pledges (amount, user_id, project_id) VALUES (19, 19, 19);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 21, 21);
INSERT INTO pledges (amount, user_id, project_id) VALUES (22, 22, 22);
INSERT INTO pledges (amount, user_id, project_id) VALUES (23, 23, 23);
INSERT INTO pledges (amount, user_id, project_id) VALUES (24, 24, 24);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 25, 25);
INSERT INTO pledges (amount, user_id, project_id) VALUES (26, 26, 26);
INSERT INTO pledges (amount, user_id, project_id) VALUES (27, 27, 27);
INSERT INTO pledges (amount, user_id, project_id) VALUES (28, 28, 28);
INSERT INTO pledges (amount, user_id, project_id) VALUES (29, 29, 29);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 30, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
